services:
  xray:
    build:
      context: .
      dockerfile: Dockerfile.xray
    container_name: familynet-vpn-xray
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "127.0.0.1:8082:8000"
      - "51821:51821/udp"
      - "443:443/tcp"
      - "8444:8443/tcp"
      - "8445:8445/tcp"
    environment:
      - SERVER_HOSTNAME=ams-1-vm-78r1
      - WG_HOST=147.45.169.35
    volumes:
      - xray-test-data:/data

volumes:
  xray-test-data:
    external: true
    name: xray-test-data
